# Generated by Django 3.1.2 on 2020-11-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('birth_date', models.DateField()),
                ('pet_type', models.CharField(max_length=10)),
                ('breed', models.CharField(max_length=50)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('vaccinated', models.BooleanField(default=False)),
                ('castrated', models.BooleanField(default=False)),
                ('dewormed', models.BooleanField(default=False)),
                ('vulnerable', models.BooleanField(default=False)),
            ],
        ),
    ]
