# Generated by Django 3.1.2 on 2020-11-16 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_pet_id_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='id_user',
            new_name='user',
        ),
    ]
